package bean;
// default package
// Generated 16/05/2015 11:39:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * TblName generated by hbm2java
 */
public class TblName implements java.io.Serializable {

	private String identificador;
	private String sector;
	private String ugel;
	private String institucion;
	private String direccion;
	private String distrito;

	public TblName() {
	}

	public TblName(String identificador) {
		this.identificador = identificador;
	}

	public TblName(String identificador, String sector, String ugel,
			String institucion, String direccion, String distrito) {
		this.identificador = identificador;
		this.sector = sector;
		this.ugel = ugel;
		this.institucion = institucion;
		this.direccion = direccion;
		this.distrito = distrito;
	}

	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	public String getUgel() {
		return this.ugel;
	}

	public void setUgel(String ugel) {
		this.ugel = ugel;
	}

	public String getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

}
